export const FETCH_STATUS_IN_PROGRESS = 'FETCH_STATUS_IN_PROGRESS';
export const FETCH_STATUS_IN_FINISHED = 'FETCH_STATUS_IN_FINISHED';
export const SET_FETCHED_USERS = 'SET_FETCHED_USERS';
export const CLEAN_USERS = 'CLEAN_USERS';
